/**
 * src/utils/licenseKeys.js
 * Verifies RSA-signed license keys using the embedded public key.
 * The private key is NEVER distributed — only the admin has it.
 */

const crypto = require('crypto');

// ── Embedded RSA Public Key ─────────────────────────────────────────
// This is the public half of the RSA-2048 keypair generated by
// tools/generate-keypair.js. It can ONLY verify signatures —
// it cannot create them. Safe to embed in distributed code.
const PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg6sAl27E0wD8xRmqpV9H
ewAc5qO3pizUvIzRQbw7zxh0yRK1VgpqVKS4bixQ9JxneNAyTY8/he6yBZdpiNlt
0kxOmeFT+qVOellLd3za6VqRUVByA2JUqEG0VDUHSBgR8HgAw29qfcF8MtTzpul2
JTT2M3rGSnuYmg2wQRjM+/+W38Yqkot6eFTW7SwrxsI6XKaGqDqmkvsd911s2uzt
wHBfgLsBN6etoJ+ewmKwdjmiHc0mEzkcBWDpOQFlV5oLTpQxoEbTeIjXtPFEej6Z
wjBdSY5/cdLnZeGp6x1J1KdDgcqN0I05cHrVfiCt9ciIp4o9WE7u0hYvsITAxFT+
tQIDAQAB
-----END PUBLIC KEY-----`;

/**
 * Decode and verify a license key string.
 * 
 * @param {string} licenseKeyString - Base64-encoded license key
 * @returns {{ valid: boolean, payload: object|null, error: string|null }}
 */
function verifyLicense(licenseKeyString) {
  try {
    // Step 1: Decode base64
    const decoded = Buffer.from(licenseKeyString.trim(), 'base64').toString('utf8');
    
    // Step 2: Parse JSON
    let licenseData;
    try {
      licenseData = JSON.parse(decoded);
    } catch {
      return { valid: false, payload: null, error: 'Invalid license key format' };
    }

    // Step 3: Validate structure
    if (!licenseData.payload || !licenseData.signature) {
      return { valid: false, payload: null, error: 'Malformed license key' };
    }

    const { payload, signature } = licenseData;

    // Step 4: Verify required payload fields
    if (!payload.company || !payload.issuedAt || !payload.licenseId) {
      return { valid: false, payload: null, error: 'Incomplete license data' };
    }

    // Step 5: Verify RSA signature
    const payloadString = JSON.stringify(payload);
    const verify = crypto.createVerify('SHA256');
    verify.update(payloadString);
    verify.end();

    const isValid = verify.verify(PUBLIC_KEY, signature, 'base64');
    if (!isValid) {
      return { valid: false, payload: null, error: 'Invalid license key — signature verification failed' };
    }

    // Step 6: Check expiry
    if (payload.expiresAt) {
      const expiryDate = new Date(payload.expiresAt + 'T23:59:59');
      if (expiryDate < new Date()) {
        return { valid: false, payload, error: `License expired on ${payload.expiresAt}` };
      }
    }

    // ✅ Valid license
    return { valid: true, payload, error: null };

  } catch (err) {
    return { valid: false, payload: null, error: 'Failed to process license key: ' + err.message };
  }
}

/**
 * Check if a license payload has expired.
 * 
 * @param {object} payload - Decoded license payload
 * @returns {boolean}
 */
function isLicenseExpired(payload) {
  if (!payload || !payload.expiresAt) return false; // Permanent license
  const expiryDate = new Date(payload.expiresAt + 'T23:59:59');
  return expiryDate < new Date();
}

module.exports = { verifyLicense, isLicenseExpired };
